// Burushaski Dictionary Dataset Metadata - Part 2
const burushaskiDictionaryPart2 = [
  { id: "38", word: "bayu", meaning: "salt", start_seconds: 6.0, end_seconds: 9.0, audio_file: "38_bayu_salt.mp3", video_file: "38_bayu_salt.mp4" },
  { id: "39", word: "hoi", meaning: "curry", start_seconds: 9.0, end_seconds: 11.0, audio_file: "39_hoi_curry.mp3", video_file: "39_hoi_curry.mp4" },
  { id: "40", word: "bua", meaning: "cow", start_seconds: 11.0, end_seconds: 14.0, audio_file: "40_bua_cow.mp3", video_file: "40_bua_cow.mp4" },
  { id: "41", word: "haghur", meaning: "horse", start_seconds: 14.0, end_seconds: 17.5, audio_file: "41_haghur_horse.mp3", video_file: "41_haghur_horse.mp4" },
  { id: "42", word: "kantai", meaning: "kite_eagle", start_seconds: 18.0, end_seconds: 20.0, audio_file: "42_kantai_kite_eagle.mp3", video_file: "42_kantai_kite_eagle.mp4" },
  { id: "43", word: "hir", meaning: "man", start_seconds: 20.0, end_seconds: 23.5, audio_file: "43_hir_man.mp3", video_file: "43_hir_man.mp4" },
  { id: "44", word: "hilas", meaning: "boy_son", start_seconds: 24.0, end_seconds: 27.5, audio_file: "44_hilas_boy_son.mp3", video_file: "44_hilas_boy_son.mp4" },
  { id: "45", word: "dasin", meaning: "girl_daughter", start_seconds: 28.0, end_seconds: 31.5, audio_file: "45_dasin_girl_daughter.mp3", video_file: "45_dasin_girl_daughter.mp4" },
  { id: "46", word: "jut", meaning: "small", start_seconds: 32.0, end_seconds: 34.5, audio_file: "46_jut_small.mp3", video_file: "46_jut_small.mp4" },
  { id: "47", word: "uyum", meaning: "big", start_seconds: 35.0, end_seconds: 37.5, audio_file: "47_uyum_big.mp3", video_file: "47_uyum_big.mp4" },
  { id: "48", word: "huk", meaning: "dog", start_seconds: 38.0, end_seconds: 40.0, audio_file: "48_huk_dog.mp3", video_file: "48_huk_dog.mp4" },
  { id: "49", word: "ja", meaning: "my_mine", start_seconds: 40.5, end_seconds: 43.0, audio_file: "49_ja_my_mine.mp3", video_file: "49_ja_my_mine.mp4" },
  { id: "50", word: "ume", meaning: "your_yours", start_seconds: 43.0, end_seconds: 46.0, audio_file: "50_ume_your_yours.mp3", video_file: "50_ume_your_yours.mp4" },
  { id: "51", word: "mi", meaning: "our", start_seconds: 46.5, end_seconds: 51.5, audio_file: "51_mi_our.mp3", video_file: "51_mi_our.mp4" },
  { id: "52", word: "ine", meaning: "his_her", start_seconds: 52.0, end_seconds: 54.0, audio_file: "52_ine_his_her.mp3", video_file: "52_ine_his_her.mp4" },
  { id: "53", word: "chhor", meaning: "quickly", start_seconds: 54.0, end_seconds: 56.0, audio_file: "53_chhor_quickly.mp3", video_file: "53_chhor_quickly.mp4" },
  { id: "54", word: "but", meaning: "much_more", start_seconds: 56.5, end_seconds: 59.0, audio_file: "54_but_much_more.mp3", video_file: "54_but_much_more.mp4" },
  { id: "55", word: "falis", meaning: "less_few", start_seconds: 59.5, end_seconds: 62.0, audio_file: "55_falis_less_few.mp3", video_file: "55_falis_less_few.mp4" },
  { id: "56", word: "gati", meaning: "together", start_seconds: 62.0, end_seconds: 65.0, audio_file: "56_gati_together.mp3", video_file: "56_gati_together.mp4" },
  { id: "57", word: "mimo", meaning: "own", start_seconds: 65.0, end_seconds: 67.5, audio_file: "57_mimo_own.mp3", video_file: "57_mimo_own.mp4" },
  { id: "58", word: "bisin", meaning: "what", start_seconds: 68.0, end_seconds: 70.0, audio_file: "58_bisin_what.mp3", video_file: "58_bisin_what.mp4" },
  { id: "59", word: "awa", meaning: "yes", start_seconds: 70.0, end_seconds: 73.0, audio_file: "59_awa_yes.mp3", video_file: "59_awa_yes.mp4" },
  { id: "60", word: "bey", meaning: "no", start_seconds: 73.0, end_seconds: 75.5, audio_file: "60_bey_no.mp3", video_file: "60_bey_no.mp4" },
  { id: "61", word: "jare", meaning: "to_me", start_seconds: 76.0, end_seconds: 78.5, audio_file: "61_jare_to_me.mp3", video_file: "61_jare_to_me.mp4" },
  { id: "62", word: "chhumo", meaning: "fish", start_seconds: 79.0, end_seconds: 81.5, audio_file: "62_chhumo_fish.mp3", video_file: "62_chhumo_fish.mp4" },
  { id: "63", word: "phash", meaning: "finished_end", start_seconds: 82.0, end_seconds: 85.0, audio_file: "63_phash_finished_end.mp3", video_file: "63_phash_finished_end.mp4" }
];
